; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
#define MyAppName "FFC Autosync Plus 2025"
#define MyAppVersion "3.4"
#define MyAppPublisher "My Company, Inc."
#define MyAppURL "https://www.example.com/"
#define MyAppExeName "FFC_Autosync_Plus.exe"
#define MyAppAssocName MyAppName + " File"
#define MyAppAssocExt ".myp"
#define MyAppAssocKey StringChange(MyAppAssocName, " ", "") + MyAppAssocExt

; กำหนด path ของ folders และ icon ที่ต้องการ copy
#define FFCFolderSource "C:\Users\tanatips\Documents\nectec\autosync\FFC"
#define ImageFolderSource "C:\Users\tanatips\Documents\nectec\autosync\src\image"
#define IconFolderSource "C:\Users\tanatips\Documents\nectec\autosync\src\resources"
; กำหนด icon file สำหรับ shortcut (ต้องเป็นไฟล์ .ico)
#define MyAppIcon "C:\Users\tanatips\Documents\nectec\autosync\src\resources\rsz_iconffc.ico"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{D1F1921E-042D-4EDE-9E0D-7CB31E8F3D32}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName=C:\AMED\{#MyAppName}
ChangesAssociations=yes
DisableProgramGroupPage=yes
; Uncomment the following line to run in non administrative install mode (install for current user only.)
;PrivilegesRequired=lowest
OutputDir=C:\Users\tanatips\Documents\nectec\autosync\output
OutputBaseFilename=FFC Autosync Plus 2025
; Icon สำหรับ installer
SetupIconFile={#MyAppIcon}
; Icon สำหรับ uninstaller
UninstallDisplayIcon={app}\src\resource\rsz_iconffc.ico
Compression=lzma
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
; Main application files
Source: "C:\Users\tanatips\Documents\nectec\autosync\dist\bundles\FFC_Autosync_Plus\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\tanatips\Documents\nectec\autosync\dist\bundles\FFC_Autosync_Plus\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs

; Copy folders to app directory
Source: "{#FFCFolderSource}\*"; DestDir: "{app}\app\FFC"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "{#ImageFolderSource}\*"; DestDir: "{app}\app\src\image"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "{#IconFolderSource}\*"; DestDir: "{app}\app\src\resource"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "{#FFCFolderSource}\*"; DestDir: "{app}\FFC"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "{#ImageFolderSource}\*"; DestDir: "{app}\src\image"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "{#IconFolderSource}\*"; DestDir: "{app}\src\resource"; Flags: ignoreversion recursesubdirs createallsubdirs

; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Registry]
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocExt}\OpenWithProgids"; ValueType: string; ValueName: "{#MyAppAssocKey}"; ValueData: ""; Flags: uninsdeletevalue
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}"; ValueType: string; ValueName: ""; ValueData: "{#MyAppAssocName}"; Flags: uninsdeletekey
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: "{app}\src\resource\rsz_iconffc.ico"
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\shell\open\command"; ValueType: string; ValueName: ""; ValueData: """{app}\{#MyAppExeName}"" ""%1"""
Root: HKA; Subkey: "Software\Classes\Applications\{#MyAppExeName}\SupportedTypes"; ValueType: string; ValueName: ".myp"; ValueData: ""

[Icons]
; Shortcut ใน Start Menu พร้อม icon
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; IconFilename: "{app}\src\resource\rsz_iconffc.ico"
; Shortcut บน Desktop พร้อม icon
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; IconFilename: "{app}\src\resource\rsz_iconffc.ico"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent