/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FFCDataBaseSetting.java
 *
 * Created on 2 ก.พ. 2554, 10:29:15
 */

package FFC_Form;

import ConnectDatabase.ConnectSQL;
import ConnectDatabase.DriverDataBase;
import FileManager.FileSettingDataBaseFFCManager;
import javax.swing.ImageIcon;
import javax.swing.JComponent;
import javax.swing.JFileChooser;
import javax.swing.JLabel;


/**
 *
 * @author Administrator
 */
public class ConfigServerForm extends javax.swing.JFrame {

    /** Creates new form FFCDataBaseSetting */
    public ConfigServerForm() {
        initComponents();
        this.setAllbg();
        setLocationRelativeTo(null);
        initComponents2();

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPaneBGDBSetting = new javax.swing.JLayeredPane();
        jButtonSettingDBClose = new javax.swing.JButton();
        javax.swing.JPanel jPanelDBSetting = new javax.swing.JPanel();
        jTextFieldServer = new javax.swing.JTextField();
        jTextFieldServerName = new javax.swing.JTextField();
        jComboBoxDriverName = new javax.swing.JComboBox();
        jTextFieldPort = new javax.swing.JTextField();
        jTextFieldUsername = new javax.swing.JTextField();
        jPasswordFieldPassword = new javax.swing.JPasswordField();
        jLabeltextName = new javax.swing.JLabel();
        jLabelTextServerName = new javax.swing.JLabel();
        jLabelTextDriverName = new javax.swing.JLabel();
        jLabelTextPort = new javax.swing.JLabel();
        jLabelTextUserName = new javax.swing.JLabel();
        jLabelTextPassword = new javax.swing.JLabel();
        jButtonOKSettingDB = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jhcisPathTextField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Config Connection DataBase");
        setResizable(false);
        setUndecorated(true);

        jLayeredPaneBGDBSetting.setBorder(new javax.swing.border.MatteBorder(new javax.swing.ImageIcon(getClass().getResource("/Image/ConfigServer_bg.png")))); // NOI18N

        jButtonSettingDBClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/close-green2.png"))); // NOI18N
        jButtonSettingDBClose.setToolTipText("close program");
        jButtonSettingDBClose.setOpaque(false);
        jButtonSettingDBClose.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/close-green20x20.png"))); // NOI18N
        jButtonSettingDBClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSettingDBCloseActionPerformed(evt);
            }
        });
        jButtonSettingDBClose.setBounds(370, 10, 21, 21);
        jLayeredPaneBGDBSetting.add(jButtonSettingDBClose, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jPanelDBSetting.setBackground(new java.awt.Color(255, 255, 255));
        jPanelDBSetting.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Config Connection DataBase", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanelDBSetting.setForeground(new java.awt.Color(255, 255, 255));
        jPanelDBSetting.setMinimumSize(new java.awt.Dimension(380, 360));
        jPanelDBSetting.setOpaque(false);
        jPanelDBSetting.setPreferredSize(new java.awt.Dimension(380, 360));

        jComboBoxDriverName.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "com.mysql.jdbc.Driver", "sun.jdbc.odbc.JdbcOdbcDriver" }));

        jPasswordFieldPassword.setForeground(new java.awt.Color(102, 102, 102));
        jPasswordFieldPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPasswordFieldPassword.setText("**********");

        jLabeltextName.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabeltextName.setText("Server Name");

        jLabelTextServerName.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabelTextServerName.setText("Database Name");

        jLabelTextDriverName.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabelTextDriverName.setText("Driver Name");

        jLabelTextPort.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabelTextPort.setText("Port");

        jLabelTextUserName.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabelTextUserName.setText("Username");

        jLabelTextPassword.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabelTextPassword.setText("Password");

        jButtonOKSettingDB.setText("OK");
        jButtonOKSettingDB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOKSettingDBActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel1.setText("JHCIS Install Path ");

        jhcisPathTextField.setText("C:\\Program Files\\jhcis");

        jButton1.setText("...");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelDBSettingLayout = new javax.swing.GroupLayout(jPanelDBSetting);
        jPanelDBSetting.setLayout(jPanelDBSettingLayout);
        jPanelDBSettingLayout.setHorizontalGroup(
            jPanelDBSettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDBSettingLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDBSettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabeltextName)
                    .addComponent(jLabelTextServerName)
                    .addComponent(jLabelTextPort)
                    .addComponent(jLabelTextDriverName)
                    .addComponent(jLabelTextUserName)
                    .addComponent(jLabelTextPassword)
                    .addComponent(jLabel1))
                .addGap(21, 21, 21)
                .addGroup(jPanelDBSettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonOKSettingDB, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswordFieldPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                    .addComponent(jTextFieldUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                    .addComponent(jComboBoxDriverName, javax.swing.GroupLayout.Alignment.TRAILING, 0, 223, Short.MAX_VALUE)
                    .addComponent(jTextFieldPort, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDBSettingLayout.createSequentialGroup()
                        .addComponent(jhcisPathTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextFieldServerName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                    .addComponent(jTextFieldServer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelDBSettingLayout.setVerticalGroup(
            jPanelDBSettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDBSettingLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDBSettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldServer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabeltextName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelDBSettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTextServerName)
                    .addComponent(jTextFieldServerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelDBSettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTextDriverName)
                    .addComponent(jComboBoxDriverName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelDBSettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTextPort))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelDBSettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTextUserName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelDBSettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPasswordFieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTextPassword))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelDBSettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jhcisPathTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonOKSettingDB)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        jPanelDBSetting.setBounds(10, 30, 380, 360);
        jLayeredPaneBGDBSetting.add(jPanelDBSetting, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jPanelDBSetting.getAccessibleContext().setAccessibleName("Please config connection JHCIS database ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPaneBGDBSetting, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPaneBGDBSetting, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOKSettingDBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOKSettingDBActionPerformed
        
        FileSettingDataBaseFFCManager fileSettingDataBaseFFCManager = new FileSettingDataBaseFFCManager();
        //Set PathFile
        fileSettingDataBaseFFCManager.setPathFile("./FFC/config_mysql_local.ffc");
        //Write data
        fileSettingDataBaseFFCManager.writeDriverDataBase(
                new DriverDataBase(jTextFieldServer.getText()
                , jTextFieldServerName.getText()
                , (String) jComboBoxDriverName.getItemAt(jComboBoxDriverName.getSelectedIndex())
                , jTextFieldPort.getText()
                , jTextFieldUsername.getText()
                , jPasswordFieldPassword.getText()));
        Service.Service.driverDatabase =  fileSettingDataBaseFFCManager.readDriverDataBase();
        //Create Server Connection
        //Service.Service.connectionSQL = new ConnectSQL();
        try {
            //DataBaseMySQL.connection();
            Service.Service.loginform.setVisible(false);
            Service.Service.loginform = new LogInForm();
            Service.Service.mainform = new MainForm();
            Service.Service.jhcisPath = this.jhcisPathTextField.getText();
            this.setVisible(false);
            this.dispose();
            //Service.Service.loginform.repaint();
            //Service.Service.loginform.setVisible(false);
            Service.Service.loginform.setVisible(true);
            //Service.mainMenuFFCAutoSync = new MainMenuFFCAutoSync();
            //Service.mainMenuFFCAutoSync.setVisible(true);
        } catch (Exception ex) {
            
            this.setVisible(false);
            this.dispose();
            new ConfigServerForm().setVisible(true);
        }
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new MainMenuFFCAutoSync().setVisible(true);
//            }
//        });
}//GEN-LAST:event_jButtonOKSettingDBActionPerformed

    private void jButtonSettingDBCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSettingDBCloseActionPerformed
        // TODO add your handling code here:
        System.exit(0);
}//GEN-LAST:event_jButtonSettingDBCloseActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JFileChooser backuuPathFileChooser = new JFileChooser();
        backuuPathFileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int result = backuuPathFileChooser.showOpenDialog(this);
        if ( result == JFileChooser.APPROVE_OPTION )
        {
            this.jhcisPathTextField.setText(backuuPathFileChooser.getSelectedFile().getPath());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConfigServerForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonOKSettingDB;
    private javax.swing.JButton jButtonSettingDBClose;
    private javax.swing.JComboBox jComboBoxDriverName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelTextDriverName;
    private javax.swing.JLabel jLabelTextPassword;
    private javax.swing.JLabel jLabelTextPort;
    private javax.swing.JLabel jLabelTextServerName;
    private javax.swing.JLabel jLabelTextUserName;
    private javax.swing.JLabel jLabeltextName;
    private javax.swing.JLayeredPane jLayeredPaneBGDBSetting;
    private javax.swing.JPasswordField jPasswordFieldPassword;
    private javax.swing.JTextField jTextFieldPort;
    private javax.swing.JTextField jTextFieldServer;
    private javax.swing.JTextField jTextFieldServerName;
    private javax.swing.JTextField jTextFieldUsername;
    private javax.swing.JTextField jhcisPathTextField;
    // End of variables declaration//GEN-END:variables

    private void setbackground(JComponent component, String imagePath){
        ImageIcon earth = new ImageIcon(imagePath);
        JLabel backlabel = new JLabel(earth);
        component.add(backlabel, new Integer(Integer.MIN_VALUE));
        backlabel.setBounds(0, 0, earth.getIconWidth(), earth.getIconHeight());
    }

    private void setAllbg(){
        this.setbackground(this.jLayeredPaneBGDBSetting,".\\src\\Image\\ConfigServer_bg.png");


    }

    private void initComponents2(){
        FileSettingDataBaseFFCManager fileSettingDataBaseFFCManager = new FileSettingDataBaseFFCManager();
       fileSettingDataBaseFFCManager.setPathFile("./FFC/config_mysql_local.ffc");
        DriverDataBase driverDataBase;
        driverDataBase = fileSettingDataBaseFFCManager.readDriverDataBase();
        jTextFieldServer.setText(driverDataBase.getServer());
        jTextFieldServerName.setText(driverDataBase.getServerName());
        jTextFieldPort.setText(driverDataBase.getPort());
        jTextFieldUsername.setText(driverDataBase.getUserName());
        jPasswordFieldPassword.setText(driverDataBase.getPassword());
        
    }

}
