/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FFCAgreement.java
 *
 * Created on 1 ก.พ. 2554, 14:32:52
 */

package FFC_Form;


import AdbManager.RunAdb;
import ConnectDatabase.ConnectSQL;
import FileManager.FileManager;
import FileManager.FileSettingDataBaseFFCManager;
import FileManager.FileUser;
import auto_sync_v2.Main;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JComponent;
import javax.swing.JLabel;

/**
 *
 * @author Administrator
 */
public class FFCAgreement extends javax.swing.JFrame {

    /** Creates new form FFCAgreement */
    public FFCAgreement() {
        initComponents();
        this.setbackground(this.jLayeredPane1, ".\\src\\Image\\Agreement_bg.png");
        this.setLocationRelativeTo(null);
    //    dateOut = new Date(111, 9, 31);
    }
        
    public boolean  regisredUser(){
        FileManager fileManager = new FileManager();
        System.out.println(fileManager.isFile("./FFC/Register_user.ffc"));
        if(fileManager.isFile("./FFC/Register_user.ffc")){
            FileUser fileUser = new FileUser();
            fileUser.setPathFile("./FFC/Register_user.ffc");
            if(fileUser.readDriverDataBase()==null){
                System.out.println("No Register");
                return false;
            }
            System.out.println("Register");
            return true;
        }
        System.exit(0);
        return false;
    }
    private void showMainMenu(){
        FileSettingDataBaseFFCManager fileSettingDataBaseFFCManager = new FileSettingDataBaseFFCManager();
            fileSettingDataBaseFFCManager.setPathFile("./FFC/config_mysql_local.ffc");
            Service.Service.driverDatabase =  fileSettingDataBaseFFCManager.readDriverDataBase();
            //Service.Service.connectionSQL = new ConnectSQL();
            Service.Service.loginform = new LogInForm();
            
            Service.Service.loginform.setVisible(true);
       /* try {
            Service.Service.loginform = new LogInForm();
            Service.Service.loginform.setVisible(true);
        } catch (Exception ex) {
            ex.printStackTrace();
                new ConfigServerForm().setVisible(true);
        }*/
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jDialogLicense = new javax.swing.JDialog();
        jLayeredPaneDialogWellcome = new javax.swing.JLayeredPane();
        jPanelDilogWellcome = new javax.swing.JPanel();
        jLabelHeadDialogWellcome = new javax.swing.JLabel();
        jButtonOKWellcomeDialog = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();

        jScrollPane2.setViewportView(jEditorPane1);

        jDialogLicense.setAlwaysOnTop(true);
        jDialogLicense.setModal(true);
        jDialogLicense.setResizable(false);
        jDialogLicense.setUndecorated(true);

        jPanelDilogWellcome.setOpaque(false);

        jLabelHeadDialogWellcome.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelHeadDialogWellcome.setForeground(new java.awt.Color(255, 0, 0));
        jLabelHeadDialogWellcome.setText("ขออภัยอย่างสูง หมดอายุการทดสอบใช้งาน");

        jButtonOKWellcomeDialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOKWellcomeDialogActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("โทรศัพท์ : 0-2564-6900 ต่อ 2513, 2529");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("email : watcharakon.noothong@nectec.or.th");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("กรุณาติดต่อทีมพัฒนาโปรแกรม FFC AutoSync+");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("วันที่ 12 ตุลาคม 2556");

        javax.swing.GroupLayout jPanelDilogWellcomeLayout = new javax.swing.GroupLayout(jPanelDilogWellcome);
        jPanelDilogWellcome.setLayout(jPanelDilogWellcomeLayout);
        jPanelDilogWellcomeLayout.setHorizontalGroup(
            jPanelDilogWellcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDilogWellcomeLayout.createSequentialGroup()
                .addGroup(jPanelDilogWellcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDilogWellcomeLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel2))
                    .addGroup(jPanelDilogWellcomeLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanelDilogWellcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)))
                    .addGroup(jPanelDilogWellcomeLayout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(jButtonOKWellcomeDialog, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDilogWellcomeLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jLabelHeadDialogWellcome)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDilogWellcomeLayout.createSequentialGroup()
                .addContainerGap(75, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(70, 70, 70))
        );
        jPanelDilogWellcomeLayout.setVerticalGroup(
            jPanelDilogWellcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDilogWellcomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelHeadDialogWellcome)
                .addGap(11, 11, 11)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonOKWellcomeDialog, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLayeredPaneDialogWellcome.add(jPanelDilogWellcome);
        jPanelDilogWellcome.setBounds(0, 0, 380, 180);

        javax.swing.GroupLayout jDialogLicenseLayout = new javax.swing.GroupLayout(jDialogLicense.getContentPane());
        jDialogLicense.getContentPane().setLayout(jDialogLicenseLayout);
        jDialogLicenseLayout.setHorizontalGroup(
            jDialogLicenseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPaneDialogWellcome, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jDialogLicenseLayout.setVerticalGroup(
            jDialogLicenseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPaneDialogWellcome, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FFC Agreement");
        setAlwaysOnTop(true);
        setUndecorated(true);
        setResizable(false);

        jLayeredPane1.setBorder(new javax.swing.border.MatteBorder(new javax.swing.ImageIcon(getClass().getResource("/Image/Agreement_bg.png")))); // NOI18N

        jButton1.setText("OK");
        jButton1.setPreferredSize(new java.awt.Dimension(65, 23));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jLayeredPane1.add(jButton1);
        jButton1.setBounds(40, 470, 79, 23);

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jLayeredPane1.add(jButton2);
        jButton2.setBounds(340, 470, 78, 23);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Software License Agreement");
        jLayeredPane1.add(jLabel1);
        jLabel1.setBounds(130, 10, 198, 17);

        jTextPane1.setEditable(false);
        jTextPane1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextPane1.setForeground(new java.awt.Color(0, 0, 153));
        jTextPane1.setText("                                ข้อตกลงการใช้บริการ\n\n    โปรดอ่านข้อตกลงฉบับนี้อย่างระมัดระวังก่อนใช้บริการและโปรดปฏิบัติ\nตามเงื่อนไข ตลอดจนข้อกำหนด  ในข้อตกลงฉบับนี้ อย่างเคร่งครัดซึ่งใน\nข้อตกลงการให้บริการนี้ ให้ “ผู้ให้บริการ”  หมายถึง ศูนย์วิจัยเทคโนโลยี \nสิ่งอำนวยความสะดวกและเครื่องมือแพทย์ คือ “ผู้รับข้อมูล” ตามพระราช\nบัญญัติข้อมูลสุขภาพ 2561 “ผู้ใช้บริการ” หมายถึง “เจ้าหน้าที่” ภายใต้\nหน่วยงานที่เป็น “ผู้ควบคุมข้อมูล” ซึ่งมีหน้าที่ให้บริการแก่ “เจ้าของข้อมูล” \nตามพระราชบัญญัติข้อมูลสุขภาพ 2561ผู้ให้บริการและผู้ใช้บริการได้ตกลง\nกันโดยมีข้อความดังต่อไปนี้ข้อตกลงฉบับนี้ เป็นการกำหนดเงื่อนไขและข้อ\nกำหนดในการใช้ “บริการ” ของ “ผู้ให้บริการ”  ไม่ว่าจะเป็นการใช้บริการ\nผ่านช่องทางใดการเข้าใช้  “บริการ”  นี้  ถือว่าผู้ใช้บริการได้ยอมรับและ  \nผูกพันตามข้อตกลงข้อควรทราบ เงื่อนไขการให้บริการ ตลอดจนข้อกำหนด\nอื่นๆภายใต้ข้อตกลงฉบับนี้  “ผู้ให้บริการ”  สงวนสิทธิ์  ในการ  เพิ่มเติม \nเปลี่ยนแปลง ยกเลิก รายละเอียด เงื่อนไข และข้อกำหนดในข้อตกลงฉบับ\nนี้ โดยมิต้องแจ้งให้ท่านทราบล่วงหน้า ผู้ใช้บริการตกลงที่จะตรวจสอบข้อตก\nลง ข้อควรทราบ เงื่อนไขการให้บริการ ตลอดจนข้อกำหนดอื่นๆ  ทุกครั้งที่\nเข้าใช้บริการ และเมื่อผู้ใช้บริการเข้าใช้บริการ   ถือว่าท่านได้ยอมรับและผูก\nพันข้อตกลง ข้อควรทราบ เงื่อนไข การให้บริการ  ตลอดจนข้อกำหนดอื่นๆ \nที่มีอยู่ ณ เวลาที่เข้าใช้บริการ\n\n- เมื่อผู้ใช้บริการลงทะเบียนเพื่อเข้าใช้บริการแล้ว เท่ากับผู้ใช้บริการยืนยันว่า\nผู้ใช้บริการได้อ่านข้อตกลงการใช้งานนี้โดยละเอียดและครบถ้วน \nและยอมรับที่จะปฏิบัติตามข้อตกลงการใช้งานของ “ผู้ให้บริการ” ทุกข้อ\n\n- ผู้ใช้บริการยินยอมให้ผู้ให้บริการเก็บข้อมูลสุขภาพของเจ้าของข้อมูลเพื่อ\nประโยชน์แก่ผู้ใช้บริการและเจ้าของข้อมูล ซึ่งผู้ให้บริการจะรักษา\nข้อมูลอย่างปลอดภัยตามมาตรฐานอุตสาหกรรมซอฟต์แวร์\n\n- ผู้ใช้บริการยินยอมให้ผู้ให้บริการสามารถนำข้อมูลสุขภาพของเจ้าของข้อ\nมูลแบบไม่ระบุตัวตนไปใช้ในการวิเคราะห์ หรือทำการวิจัยเพื่อ\nพัฒนาคุณภาพชีวิตของประชาชน\n\n- ผู้ใช้บริการจะต้องปฏิบัติตามเงื่อนไขภายใต้ข้อตกลงการให้บริการโดย\nเคร่งครัด รวมถึงการปฏิบัติตามนโยบาย ประกาศ คำสั่ง ระเบียบ และข้อ\nบังคับของผู้ให้บริการ ตลอดจนกฎหมายที่เกี่ยวข้องกับการใช้บริการทั้งที่ใช้\nอยู่ในปัจจุบันและที่จะเกิดขึ้นในอนาคต อาทิ พระราชบัญญัติว่าด้วยการกระ\nทำความผิดทางคอมพิวเตอร์ พ.ศ. 2550, พระราชบัญญัติว่าด้วยธุรกรรม\nอิเล็กทรอนิกส์ พ.ศ. 2544, ระเบียบกระทรวงสาธารณสุขว่าด้วยการคุ้ม\nครองและจัดการข้อมูลด้านสุขภาพของบุคคล พ.ศ.2561 เป็นต้น\n\n- ผู้ให้บริการไม่ต้องรับผิดในความเสียหายที่เกิดขึ้นจากเหตุสุดวิสัยต่างๆ \nหรือเหตุการณ์ที่ผู้ให้บริการไม่สามารถควบคุมได้ ซึ่งรวมถึงการที่อุปกรณ์ \nระบบสื่อสาร หรือการส่งสัญญาณเชื่อมต่อไม่ทำงาน หรือการรบกวนจากไวรัส\nคอมพิวเตอร์ หรือจากการกระทำที่ไม่ชอบด้วยกฎหมาย หรือในกรณีที่ผู้ให้\nบริการปิดให้บริการนี้ เพื่อปรับปรุงหรือบำรุงรักษาระบบ อันเป็นเหตุให้ผู้ใช้\nบริการไม่สามารถใช้บริการนี้ได้\n\n- ผู้ใช้บริการจะต้องรักษาชื่อบัญชีผู้ใช้งานและรหัสผ่านไว้เป็นความลับ \nหากปรากฏว่ามีผู้อื่นสามารถใช้งานผ่านบัญชีของผู้ใช้บริการได้ ผู้ให้บริการ\nจะไม่รับผิดชอบต่อความเสียหายที่เกิดขึ้น\n\n- ผู้ให้บริการไม่รับผิดความเสียหายใดๆ ที่เกิดขึ้นจากการใช้บัญชีส่วนตัว\nของผู้ใช้บริการ หรืออนุญาตให้บุคคลใดใช้บัญชีส่วนตัวของตน \nทั้งนี้ท่านจะไม่ใช้บัญชีส่วนตัว ของบุคคลอื่นเช่นกัน\n\n- ผู้ใช้บริการจะต้องยินยอมให้ผู้ให้บริการเก็บข้อมูลพฤติกรรมการใช้บริการ\nเพื่อปรับปรุงการให้บริการ\n\n- ผู้ใช้บริการตกลงจะไม่ใช้ถ้อยคำที่ไม่เหมาะสมระหว่างการใช้บริการกรณี\nฉุกเฉินอย่างไรก็ตามผู้ให้บริการไม่สามารถรับประกันได้ว่ามาตรการรักษา \nความปลอดภัยของผู้ให้บริการจะไม่ถูกล่วงล้ำ หรือนำไปสู่การใช้ข้อมูลส่วน\nบุคคลของผู้ใช้บริการและ/หรือเจ้าของข้อมูล เพื่อวัตถุประสงค์ที่ไม่เหมาะสม \nทั้งนี้หากผู้ใช้บริการพบปัญหา หรือ ช่องโหว่ด้านความปลอดภัย \n\n- ผู้ใช้บริการมีหน้าที่แจ้งให้ทางผู้ให้บริการทราบเพื่อแก้ไขปัญหาดังกล่าว\nเนื้อหา ข้อความ รูปแบบ ของบริการนี้เป็นลิขสิทธิ์ของผู้ให้บริการ การทำ\nซ้ำ ลอกเลียนดัดแปลง คัดลอก กระจายหรือจำหน่ายจ่ายแจก บางส่วน\nหรือทั้งหมดจากทรัพย์สินทางปัญญานี้โดยมิได้รับอนุญาตจากเจ้าของลิขสิทธิ์\nเป็นลายลักษณ์อักษร ถือเป็นการกระทำอันผิดกฎหมายอันเป็นการละเมิด \nและผู้กระทำความผิดจะได้รับโทษตามที่กฎหมายได้กำหนดไว้");
        jScrollPane1.setViewportView(jTextPane1);

        jLayeredPane1.add(jScrollPane1);
        jScrollPane1.setBounds(30, 40, 396, 410);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 449, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        RunAdb runAdb = new RunAdb("./FFC/adb/adbKillServer.bat");
        runAdb.runAdb();
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:                
        if(regisredUser()){
            this.setVisible(false);
            this.dispose();
            showMainMenu();
        }else{
            this.setVisible(false);
            this.dispose();
            //new FFCRegisterUser().setVisible(true);
           showMainMenu();
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    //การกำหนดให้โปรแกรมทำงานหรือไม่ กรณีหมดอายุการใช้งาน Date_expire
    private void jButtonOKWellcomeDialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOKWellcomeDialogActionPerformed
                
        // if you needs this program close when date expired
        // Please uncheck comment System.exit(0)
        // โปรแกรมจะปิดตัวเองทันที ไม่สามารถเรียกใช้งานได้
         System.exit(0);
        
        // if you want to don't close when date expired
        // Please uncheck comment all line belows.
        // โปรแกรม เพียงแค่แจ้งเตือน เท่านั้น แต่สามารถใช้งานได้ปกติ
          jDialogLicense.show(false);
          this.setEnabled(true);
          this.repaint();
    }//GEN-LAST:event_jButtonOKWellcomeDialogActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FFCAgreement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonOKWellcomeDialog;
    private javax.swing.JDialog jDialogLicense;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelHeadDialogWellcome;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPaneDialogWellcome;
    private javax.swing.JPanel jPanelDilogWellcome;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables

    
   
    public void checkDateOut(){
        Date date = new Date(); // วันปัจจุบัน ปี AD. เสมอ
        Date dateOut = new Date(113, 10, 12); // วันหมดอายุ (ปี(AD)+1900,เดือน 0 - 11, วัน 1 -31);
        System.out.println("now date : "+date);   
        System.out.println("dateExpire : "+dateOut);       
        /*this.setVisible(true);
        this.setEnabled(false);       
        try {
            Thread.sleep(1500);
        } catch (InterruptedException ex) {
            Logger.getLogger(FFCAgreement.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setEnabled(true); */
        if(!regisredUser()){
            if(date.after(dateOut)){
                    jDialogLicense.setSize(380, 180);
                    jDialogLicense.setLocation(this.getX()
                        +((this.getWidth()/2)-(jDialogLicense.getWidth()/2))
                        ,this.getY()
                        +((this.getHeight()/2)-(jDialogLicense.getHeight()/2)));
                        this.setEnabled(false);
                        jDialogLicense.show(true);
            }
            else{
                Main.openRegisterUserform();
            }        }else{
            this.setVisible(true);
            
        }
    }

    private void setbackground(JComponent component, String imagePath){
        ImageIcon image = new ImageIcon(imagePath);
        JLabel label = new JLabel(image);
        component.add(label, new Integer(Integer.MIN_VALUE));
        label.setBounds(0, 0, image.getIconWidth(), image.getIconHeight());
    }

}
