/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FFCRegisterUser.java
 *
 * Created on May 17, 2011, 5:18:55 PM
 */
package FFC_Form;





import FileManager.FileUser;
import MailManager.SendMail;
import User.UserData;
import javax.swing.JOptionPane;
import java.net.InetAddress;
import java.net.UnknownHostException;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JComponent;
import javax.swing.JLabel;

/**
 *
 * @author pi
 */
public class FFCRegisterUser extends javax.swing.JFrame {

   
    /** Creates new form FFCRegisterUser */
    public FFCRegisterUser() {
        initComponents();
        this.setAllbg();
        this.setLocationRelativeTo(null);
        this.sendMailDialog.setLocationRelativeTo(null);
        this.sendMailProgressBar.setIndeterminate(true);
    }
    public void showMainMenu(){
                
        try {
            FFCAgreement ffcAgreement = new FFCAgreement();
            ffcAgreement.setVisible(true);
            //Service.mainMenuFFCAutoSync = new MainMenuFFCAutoSync();
            //Service.mainMenuFFCAutoSync.setVisible(true);
        } catch (Exception ex) {
            ex.printStackTrace();
               // new FFCDataBaseSetting().setVisible(true);
        }
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialogGernaral = new javax.swing.JDialog();
        jLayeredPaneDialogGernaral = new javax.swing.JLayeredPane();
        jPanelDialogGernaral = new javax.swing.JPanel();
        jButtonOKGerraralDialog = new javax.swing.JButton();
        jLabelIconDialogGernaral = new javax.swing.JLabel();
        messageText = new javax.swing.JTextField();
        sendMailDialog = new javax.swing.JDialog();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jLabel12 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        sendMailProgressBar = new javax.swing.JProgressBar();
        jLabel17 = new javax.swing.JLabel();
        sendMailTimeLabel = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();

        jDialogGernaral.setAlwaysOnTop(true);
        jDialogGernaral.setModal(true);
        jDialogGernaral.setResizable(false);
        jDialogGernaral.setUndecorated(true);

        jPanelDialogGernaral.setInheritsPopupMenu(true);
        jPanelDialogGernaral.setOpaque(false);

        jButtonOKGerraralDialog.setText("OK");
        jButtonOKGerraralDialog.setMaximumSize(new java.awt.Dimension(69, 21));
        jButtonOKGerraralDialog.setMinimumSize(new java.awt.Dimension(69, 21));
        jButtonOKGerraralDialog.setPreferredSize(new java.awt.Dimension(69, 21));
        jButtonOKGerraralDialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOKGerraralDialogActionPerformed(evt);
            }
        });

        jLabelIconDialogGernaral.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/error.png"))); // NOI18N

        messageText.setColumns(10);
        messageText.setEditable(false);
        messageText.setFont(new java.awt.Font("Tahoma", 1, 12));
        messageText.setText("Message");
        messageText.setAutoscrolls(false);
        messageText.setBorder(null);
        messageText.setDoubleBuffered(true);
        messageText.setDragEnabled(true);
        messageText.setFocusable(false);
        messageText.setOpaque(false);

        javax.swing.GroupLayout jPanelDialogGernaralLayout = new javax.swing.GroupLayout(jPanelDialogGernaral);
        jPanelDialogGernaral.setLayout(jPanelDialogGernaralLayout);
        jPanelDialogGernaralLayout.setHorizontalGroup(
            jPanelDialogGernaralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDialogGernaralLayout.createSequentialGroup()
                .addGroup(jPanelDialogGernaralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDialogGernaralLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelIconDialogGernaral, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                        .addGap(10, 10, 10)
                        .addComponent(messageText, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17))
                    .addGroup(jPanelDialogGernaralLayout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(jButtonOKGerraralDialog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanelDialogGernaralLayout.setVerticalGroup(
            jPanelDialogGernaralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDialogGernaralLayout.createSequentialGroup()
                .addGroup(jPanelDialogGernaralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDialogGernaralLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelIconDialogGernaral, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelDialogGernaralLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(messageText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(9, 9, 9)
                .addComponent(jButtonOKGerraralDialog, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelDialogGernaral.setBounds(0, 0, 290, 160);
        jLayeredPaneDialogGernaral.add(jPanelDialogGernaral, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDialogGernaralLayout = new javax.swing.GroupLayout(jDialogGernaral.getContentPane());
        jDialogGernaral.getContentPane().setLayout(jDialogGernaralLayout);
        jDialogGernaralLayout.setHorizontalGroup(
            jDialogGernaralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPaneDialogGernaral, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jDialogGernaralLayout.setVerticalGroup(
            jDialogGernaralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPaneDialogGernaral, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        sendMailDialog.setMinimumSize(new java.awt.Dimension(330, 180));

        jLayeredPane2.setBorder(new javax.swing.border.MatteBorder(new javax.swing.ImageIcon(getClass().getResource("/Image/FFC_Background/sendMaildialog_bg.png")))); // NOI18N

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel12.setText("กำลังส่งข้อมูลการลงทะเบียน");
        jLabel12.setBounds(80, 10, 158, 25);
        jLayeredPane2.add(jLabel12, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel10.setText("กรุณารอสักครู่...");
        jLabel10.setBounds(20, 47, 90, 30);
        jLayeredPane2.add(jLabel10, javax.swing.JLayeredPane.DEFAULT_LAYER);
        sendMailProgressBar.setBounds(20, 80, 276, 22);
        jLayeredPane2.add(sendMailProgressBar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel17.setText("Time :");
        jLabel17.setBounds(20, 110, 46, -1);
        jLayeredPane2.add(jLabel17, javax.swing.JLayeredPane.DEFAULT_LAYER);

        sendMailTimeLabel.setText("0");
        sendMailTimeLabel.setBounds(80, 110, 22, -1);
        jLayeredPane2.add(sendMailTimeLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel16.setText("Sec.");
        jLabel16.setBounds(110, 110, 40, -1);
        jLayeredPane2.add(jLabel16, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout sendMailDialogLayout = new javax.swing.GroupLayout(sendMailDialog.getContentPane());
        sendMailDialog.getContentPane().setLayout(sendMailDialogLayout);
        sendMailDialogLayout.setHorizontalGroup(
            sendMailDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
        );
        sendMailDialogLayout.setVerticalGroup(
            sendMailDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Register User");
        setResizable(false);
        setUndecorated(true);

        jLayeredPane1.setBorder(new javax.swing.border.MatteBorder(new javax.swing.ImageIcon(getClass().getResource("/Image/register_bg.png")))); // NOI18N

        jPanel1.setMinimumSize(new java.awt.Dimension(450, 300));
        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(450, 300));

        jLabel1.setText("Name");

        jLabel2.setText("Last Name");

        jLabel4.setText("Organizations");

        jLabel3.setText("Telephone");

        jButton1.setText("Register");
        jButton1.setOpaque(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Register Later");
        jButton2.setOpaque(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel5.setText("E-mail");

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jPanel2.setOpaque(false);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Register User Information");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jLabel6)
                .addContainerGap(85, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField5)
                                    .addComponent(jTextField4)
                                    .addComponent(jTextField3)
                                    .addComponent(jTextField2)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE))
                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE))
                    .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE))
                    .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 14, Short.MAX_VALUE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );

        jPanel1.setBounds(0, 0, 340, 350);
        jLayeredPane1.add(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        this.dispose();
        showMainMenu();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(jTextField1.getText().length() <1){
            JOptionPane.showMessageDialog(this,
            "กรุณากรอกชื่อของท่าน",
            "Warning !!!",
            JOptionPane.WARNING_MESSAGE);
            //showGernaralDialog("Please fill in Name");
            return;
        }
                
        if(jTextField2.getText().length() <1){
            JOptionPane.showMessageDialog(this,
            "กรุณากรอกนามสกุลของท่าน",
            "Warning !!!",
            JOptionPane.WARNING_MESSAGE);
            //showGernaralDialog("Please fill in LaseName");
            return;
        }
                        
        if(jTextField3.getText().length() <1){
            JOptionPane.showMessageDialog(this,
            "กรุณากรอกเบอร์โทรของท่าน",
            "Warning !!!",
            JOptionPane.WARNING_MESSAGE);
            //showGernaralDialog("Please fill in Possition");
            return;
        }
        if(jTextField3.getText().length() <6){
            //showGernaralDialog("เบอร์โทรขั้นต่ำ6หลัก");
            JOptionPane.showMessageDialog(this,
            "กรุณากรอกเบอร์โทรขั้นต่ำ 6 หลัก",
            "Warning !!!",
            JOptionPane.WARNING_MESSAGE);
            return;
        }
        try{
        Integer integer = new Integer(jTextField3.getText());
        }catch(NumberFormatException ex){
            //showGernaralDialog("เบอร์โทรต้องเป็นตัวเลข");
            JOptionPane.showMessageDialog(this,
            "เบอร์โทรต้องเป็นตัวเลขเท่านั้น",
            "Warning !!!",
            JOptionPane.WARNING_MESSAGE);
            return;
        }
                        
        if(jTextField4.getText().length() <1){
            JOptionPane.showMessageDialog(this,
            "กรุณากรอกหน่วยงานของท่าน",
            "Warning !!!",
            JOptionPane.WARNING_MESSAGE);
            //showGernaralDialog("Please fill in Organization");
            return;
        }
                                        
        if(jTextField5.getText().length() <1){
            JOptionPane.showMessageDialog(this,
            "กรุณากรอก E-mail ของท่าน",
            "Warning !!!",
            JOptionPane.WARNING_MESSAGE);
            //showGernaralDialog("Please fill in address");
            return;
        }
        if(jTextField5.getText().indexOf("@")== -1){
            //showGernaralDialog("Email ไม่ถูกต้อง");
            JOptionPane.showMessageDialog(this,
            "E-mail ของท่านไม่ถูกต้อง",
            "Warning !!!",
            JOptionPane.WARNING_MESSAGE);
            return;
        }

        if(jTextField5.getText().indexOf(".") == -1){
            //showGernaralDialog("Email ไม่ถูกต้อง");
            JOptionPane.showMessageDialog(this,
            "E-mail ของท่านไม่ถูกต้อง",
            "Warning !!!",
            JOptionPane.WARNING_MESSAGE);
            return;
        }
        //this.setVisible(false);
        //this.dispose();
        String[] toMail = {"kitalo17@gmail.com"};
       // String[] toMail = {"fantasy_atlove@hotmail.com"};
        UserData userData = new UserData(jTextField1.getText()
                , jTextField2.getText()
                , jTextField3.getText()
                , jTextField4.getText()
                , jTextField5.getText());

        InetAddress address = null;
        try {
            address = InetAddress.getLocalHost();
        } catch (UnknownHostException ex) {

        }

        SendMail sendMail = new SendMail();
        sendMail.setVariable("ffcautosync@gmail.com","nectecffc"
                    ,"smtp.gmail.com","465","true","true",true
                    ,"javax.net.ssl.SSLSocketFactory","false"
                    ,toMail,"FFC Autosync 2012 Register User"
                    ," Name : "+jTextField1.getText()
                    +"\n LastName : "+jTextField2.getText()
                    +"\n Tel : "+jTextField3.getText()
                    +"\n Organizations : "+jTextField4.getText()
                    +"\n Address : "+jTextField5.getText()
                    +"\n IP : " +address.getHostAddress()
                    +"\n Date : "+new Date());

        sendMail.getUserData(userData);
        Thread sendMailThread = new Thread(sendMail);
        sendMail.getThread(sendMailThread);
        sendMailThread.start();
        //this.sendMailDialog.setVisible(true);
       /* Thread time = new Thread(countTime);

        time.start();
        Service.Service.dialog = new Dialog();
        Service.Service.dialog.setVisibleDialog(true);
        
            this.setEnabled(false);
       
        Service.Service.dialog.setVisibleDialog(false);*/
        /*    if(!sendMail.sendMail()){
            JOptionPane.showMessageDialog(this,
            "ไม่สามารถเชื่อมต่ออินเตอร์เน็ต",
            "error",
            JOptionPane.ERROR_MESSAGE);
            //showGernaralDialog("Connection Error");
        
        }else{
        FileUser fileUser = new FileUser();
        fileUser.setPathFile("./FFC/Register_user.ffc");
        fileUser.writeDriverDataBase(userData);
        showMainMenu();
        
        }*/
    }//GEN-LAST:event_jButton1ActionPerformed
private void showGernaralDialog(String message){
    messageText.setText(message);
        jDialogGernaral.setSize(290, 160);
        jDialogGernaral.setLocation(this.getX()
                +((this.getWidth()/2)-(jDialogGernaral.getWidth()/2))
                ,this.getY()
                +((this.getHeight()/2)-(jDialogGernaral.getHeight()/2)));
        this.setEnabled(false);
        jDialogGernaral.show(true);
    }
    private void jButtonOKGerraralDialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOKGerraralDialogActionPerformed
        // TODO add your handling code here:
        jDialogGernaral.show(false);
        this.setEnabled(true);
        this.repaint();
}//GEN-LAST:event_jButtonOKGerraralDialogActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new FFCRegisterUser().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonOKGerraralDialog;
    private javax.swing.JDialog jDialogGernaral;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelIconDialogGernaral;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLayeredPane jLayeredPaneDialogGernaral;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelDialogGernaral;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField messageText;
    private javax.swing.JDialog sendMailDialog;
    private javax.swing.JProgressBar sendMailProgressBar;
    private javax.swing.JLabel sendMailTimeLabel;
    // End of variables declaration//GEN-END:variables

    private void setbackground(JComponent component, String imagePath){
        ImageIcon earth = new ImageIcon(imagePath);
        JLabel backlabel = new JLabel(earth);
        component.add(backlabel, new Integer(Integer.MIN_VALUE));
        backlabel.setBounds(0, 0, earth.getIconWidth(), earth.getIconHeight());
    }

    private void setAllbg(){
        this.setbackground(this.jLayeredPane1, ".\\src\\Image\\register_bg.png");
        this.setbackground(this.jLayeredPane2, ".\\src\\Image\\sendMaildialog_bg.png");
    }

    public void showSendMailDialog(boolean set){
        this.sendMailDialog.setVisible(true);
    }
    
    public void setTextTimeLabel(String Text){
        this.sendMailTimeLabel.setText(Text);
    }



     public void setVisibleSendMailDialog(boolean set){
         this.sendMailDialog.setVisible(set);
     }

}

