/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * LogInForm.java
 *
 * Created on 28 เม.ย. 2554, 15:54:33
 */
package FFC_Form;
import AdbManager.RunAdb;
import Service.Service;
import java.sql.*;
import auto_sync_v2.Main;
import User.User;
import java.awt.Frame;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import ConnectDatabase.ConnectSQL;
import java.awt.Component;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JComponent;
import javax.swing.JLabel;
import java.math.BigInteger;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;

import java.nio.charset.Charset;
import java.nio.charset.StandardCharsets;
 
/**
 *
 * @author PeeT
 */
public class LogInForm extends javax.swing.JFrame {
    
    ResultSet rs;
    String[] userInformation;
    private static final Charset UTF_8 = StandardCharsets.UTF_8;
    private static final String OUTPUT_FORMAT = "%-20s:%s";
    /** Creates new form LogInForm */
    public LogInForm() {
        initComponents();
        this.setAllbg();
        Service.connectionSQL = new ConnectSQL();
        getUser();
        setLocationRelativeTo(null);
        userInformation = new String[4];
        
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane2 = new javax.swing.JLayeredPane();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        logInButton = new javax.swing.JButton();
        passwordField = new javax.swing.JPasswordField();
        userComboBox = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImages(null);
        setResizable(false);
        setUndecorated(true);

        jLayeredPane2.setBorder(new javax.swing.border.MatteBorder(new javax.swing.ImageIcon(getClass().getResource("/Image/bg_login_1.jpg")))); // NOI18N

        jLayeredPane1.setBorder(new javax.swing.border.MatteBorder(new javax.swing.ImageIcon(getClass().getResource("/Image/head_main_mini_new.jpg")))); // NOI18N

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/minimize-green20x20.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.setBounds(460, 0, 20, 20);
        jLayeredPane1.add(jButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/close-green20x20.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.setBounds(480, 0, 20, 20);
        jLayeredPane1.add(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLayeredPane1.setBounds(10, 10, 500, 70);
        jLayeredPane2.add(jLayeredPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        logInButton.setText("Log In");
        logInButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logInButtonActionPerformed(evt);
            }
        });
        logInButton.setBounds(210, 200, 76, 34);
        jLayeredPane2.add(logInButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        passwordField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passwordFieldKeyPressed(evt);
            }
        });
        passwordField.setBounds(210, 160, 138, 30);
        jLayeredPane2.add(passwordField, javax.swing.JLayeredPane.DEFAULT_LAYER);

        userComboBox.setMinimumSize(new java.awt.Dimension(28, 18));
        userComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userComboBoxActionPerformed(evt);
            }
        });
        userComboBox.setBounds(210, 120, 138, 30);
        jLayeredPane2.add(userComboBox, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 13));
        jLabel1.setText("ชื่อผู้ใช้");
        jLabel1.setBounds(150, 130, 40, -1);
        jLayeredPane2.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 13));
        jLabel2.setText("รหัสผ่าน");
        jLabel2.setBounds(150, 170, 50, -1);
        jLayeredPane2.add(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton3.setText("Setting Database");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jButton3.setBounds(10, 230, 130, 30);
        jLayeredPane2.add(jButton3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logInButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logInButtonActionPerformed
        try {
            // TODO add your handling code here:
            //MainForm mainform = new MainForm();
            Service.mainform = new MainForm();
            System.out.println(passwordField.getText());
            //String password = "xxxxxxxx";
            String query = "select * from user where username = " + '"' + userComboBox.getSelectedItem() + '"';
            System.out.println(query);
            rs = Service.connectionSQL.getResultSet(query);
            if (rs == null) {
                System.out.println("xxxxxxxxxxxxxxxx");
            }
              
            while (rs.next()) {
                userInformation[0] = rs.getString("username");
                userInformation[1] = rs.getString("password");
                userInformation[2] = rs.getString("fullname");
                userInformation[3] = rs.getString("officerposition");
                //password = rs.getString("password");
                //Service.user = new User(rs.getString(2), rs.getString(3), rs.getString(5), rs.getString(7));
            }
             byte[] md5InBytes = digest(passwordField.getText().getBytes(UTF_8));
             String hashPassword = bytesToHex(md5InBytes);
             System.out.println(String.format(OUTPUT_FORMAT, "MD5 (hex) ", bytesToHex(md5InBytes)));
            if (userInformation[1].equals(passwordField.getText()) || userInformation[1].equals(hashPassword) ) {
                System.out.println("yes");
                //System.out.println(userInformation[2]);
                Service.user = new User(userInformation[0], userInformation[1], userInformation[2], userInformation[3]);
                System.out.println(Service.user.getFullname());
                this.passwordField.setText("");
                this.userComboBox.setSelectedIndex(0);
                MainForm.setUser();
                Service.loginform.setVisible(false);
                Service.mainform.setVisible(true);
                
                if (!this.checkAdjustDatabase()) {
                    AdjustDatabase.AdjustDatabase adjust = new AdjustDatabase.AdjustDatabase();
                    Thread adjustThread = new Thread(adjust);
                    adjust.getAdjustThread(adjustThread);
                    adjustThread.start();
                }
            } else {
                System.out.println("No");
                JOptionPane.showMessageDialog(this, "รหัสผ่านผิดพลาด !!!");
            }

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(LogInForm.class.getName()).log(Level.SEVERE, null, ex);

        } catch (SQLException ex) {
            Logger.getLogger(LogInForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_logInButtonActionPerformed
 private static byte[] digest(byte[] input) {
        MessageDigest md;
        try {
            md = MessageDigest.getInstance("MD5");
        } catch (NoSuchAlgorithmException e) {
            throw new IllegalArgumentException(e);
        }
        byte[] result = md.digest(input);
        return result;
    }

    private static String bytesToHex(byte[] bytes) {
        StringBuilder sb = new StringBuilder();
        for (byte b : bytes) {
            sb.append(String.format("%02x", b));
        }
        return sb.toString();
    }
    private void userComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userComboBoxActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.setState(Frame.ICONIFIED);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        RunAdb runAdb = new RunAdb("./FFC/adb/adbKillServer.bat");
        runAdb.runAdb();
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        new ConfigServerForm().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void passwordFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordFieldKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == 10){
            this.logInButton.doClick();
        }
    }//GEN-LAST:event_passwordFieldKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new LogInForm().setVisible(true);
            }
        });
    }
    
    private void getUser()
    {
        
        try
        {
            rs = Service.connectionSQL.getResultSet("select username from user");
            while(rs.next())
            {
                userComboBox.addItem(rs.getString(1));
            }
        }
        catch(Exception e)
        {
            this.setVisible(true);
            //e.printStackTrace();
            //e.getStackTrace();
        }
    }

    private void setbackground(JComponent component, String imagePath){
        ImageIcon earth = new ImageIcon(imagePath);
        JLabel backlabel = new JLabel(earth);
        component.add(backlabel, new Integer(Integer.MIN_VALUE));
        backlabel.setBounds(0, 0, earth.getIconWidth(), earth.getIconHeight());
    }

    private void setAllbg(){
        this.setbackground(this.jLayeredPane1,".\\src\\Image\\head_main_mini_new.png");
        this.setbackground(this.jLayeredPane2,".\\src\\Image\\bg_login_1.jpg");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JButton logInButton;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JComboBox userComboBox;
    // End of variables declaration//GEN-END:variables

    private boolean checkAdjustDatabasee(){
        FileManager.FileBehavior fileBehavior = new FileManager.FileBehavior();
        fileBehavior.setPathData("./FFC/check_database.ffc");
        ArrayList<String> data = fileBehavior.readDataMultipleline();
        String dataSplit[] = data.get(0).split("=");
        System.out.println(dataSplit[1]);
        System.out.println(data);
        if(dataSplit[1].equals("true")){
            return true;
        }else{
            return false;
        }
        //return true;
    }

    private boolean checkAdjustDatabase() throws SQLException, ClassNotFoundException{
        AdjustDatabase.AdjustDatabaseManager adjustmanager = new AdjustDatabase.AdjustDatabaseManager();
        if(adjustmanager.getAdjustAll()==0){
            adjustmanager.closeConnection();
            return false;
        }else{
            adjustmanager.closeConnection();
            return true;
        }
    }

}
